name: CI

on: [pull_request]

jobs:

  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: setup pnpm
        run: corepack enable

      - name: Install dependencies
        run: pnpm install

      - name: Run check
        run: pnpm check
